CREATE USER read_user WITH LOGIN PASSWORD 'DB_PASSWORD'
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

CREATE DATABASE warehouse;
GRANT CONNECT ON DATABASE warehouse TO read_user;
GRANT USAGE ON SCHEMA public TO read_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO read_user;