version: '3.5'
services:

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_NAME}
#    restart: always
    env_file:
    - api.local.env
    ports:
    - ${POSTGRES_PORT}:5432
    networks:
    - nitrogen
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - ${POSTGRES_PATH}:/var/lib/postgresql/data:z
    - ./initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: ${RABITTMQ_IMAGE}
    container_name: ${RABITTMQ_NAME}
    env_file:
    - api.local.env
#    restart: always
    ports:
    - ${RABITTMQ_PORT}:5672
    networks:
    - nitrogen

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_NAME}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ${REDIS_PATH}:/data
    networks:
      - nitrogen      

  minio:
    image: ${MINIO_IMAGE}
    container_name: ${MINIO_NAME}
    env_file:
      - api.local.env
    ports:
    - ${MINIO_PORT}:9000
#    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: "minio server --config-dir /config /data"
    networks:
    - nitrogen

networks:
  nitrogen:
    name: nitrogen
